### PR TITLE
SteamVR v1 Support

### LINKED ISSUE #1: Vive Lighthouse (SteamVR v1) Support
If there's anyone that has Vive lighthouses that can help test please comment, I would like to add support but I can't test.

If you know how to add the support yourself I welcome a pull request as well. 

The current code does not have support for it.

### PR DESCRIPTION
**Pull request by ShayBox**

### CODE REVIEW

**Comment by ShayBox** [comment]
I have yet to do the filling in of the cmd, but what do you think of the current layout @tsjost

**Comment by tsjost** [comment]
Looks good! It's able to wake my lighthouse up!

If you want to make sure you're targeting the right device instead of blasting every base station, you'll have to either have an input for the MAC address to filter on, or, more elegantly I think, have the user specify the full 8 hexchar ID and use the last 4 to filter on the device name‽

**Comment by ShayBox** [comment]
So the id on the back of the basestation also contains part of the mac?

**Comment by tsjost** [comment]
No. The last 4 hexchars of the ID are present at the end of the bluetooth name (which is 6 hexchars). The first 2 hexchars in the name is the last byte of the MAC address.

The first 4 hexchars of the ID are not in the MAC nor the bluetooth device name; hence why they need to be retrieved by looking at the back of the device. (The full 32 bit ID is also blasted out in the OOTX/laser data which is how Steam knows about it, but then you need to have a headset hooked up and be able to communicate with it or however you access that data)

**Comment by ShayBox** [comment]
So this? `|name| name.contains("HTC BS") && name[..4] == args[2][..4]`

**Comment by tsjost** [comment]
I think `[..4]` will do a substr from the _beginning_? But yes, the last 4 hexchars of the bluetooth device name should match the last 4 hexchars of the ID/arg2 (assuming the user specifies the full 8 hexchars and not just the initial 4).

**Comment by ShayBox** [comment]
Right, thanks

**Comment by ShayBox** [comment]
Okay, is this right and does it work?

**Comment by tsjost** [comment]
```
thread 'main' panicked at 'begin <= end (9 <= 4) when slicing `HTC BS 0DB11B`', src/main.rs:43:24
```
I think the slice operator thingy is `from..to`, not `from..length`, and I guess `String::parse()` only works with 0-9 and not a-f.

This patch makes powering on and off work:
```diff
diff --git a/src/main.rs b/src/main.rs
index 168ba76..5d0e95c 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -40,20 +40,15 @@ pub fn main() {
         let lighthouses_v1 = central.peripherals().into_iter().filter(|p| {
             p.properties().local_name.iter().any(|name| {
                 name.starts_with("HTC BS")
-                    && name[(name.len() - 4)..4] == args[2][(args[2].len() - 4)..4]
+                    && name[(name.len() - 4)..] == args[2][(args[2].len() - 4)..]
             })
         });

         for lighthouse in lighthouses_v1 {
-            let name = match lighthouse.properties().local_name {
-                Some(s) => s,
-                None => exit(1),
-            };
-
-            let dd = name[(name.len() - 2)..4].parse().unwrap();
-            let cc = name[(name.len() - 4)..2].parse().unwrap();
-            let bb = args[2][2..4].parse().unwrap();
-            let aa = args[2][0..2].parse().unwrap();
+            let dd = u8::from_str_radix(&args[2][6..8], 16).unwrap();
+            let cc = u8::from_str_radix(&args[2][4..6], 16).unwrap();
+            let bb = u8::from_str_radix(&args[2][2..4], 16).unwrap();
+            let aa = u8::from_str_radix(&args[2][0..2], 16).unwrap();

             if args[1] == "off" {
                 cmd = vec![
```
(dd and cc can be retrieved from the 2nd argument as well)

**Comment by ShayBox** [comment]
So this works? it can be merged?

**Comment by tsjost** [comment]
Yep, I pulled down your apply commit and it's working great! Thanks!

(Although it takes ~18 seconds to run but except from the 5s scanning sleep it's probably due to library stuff)

**Comment by ShayBox** [comment]
What version of bluez do you have installed, I'm using 5.56

**Comment by tsjost** [comment]
Also 5.56

**Comment by ShayBox** [comment]
Interesting, probably a library issue, mine takes less time, maybe because of the length of whats being sent

**Comment by ShayBox** [comment]
wait the last 4 of the id are always B11B?

**Comment by tsjost** [comment]
Nope, my lighthouses are different.

**Comment by ShayBox** [comment]
Oh ok

**Pull request merged**
